spring.application.name=myvanitys-api
spring.profiles.active=local
# Actuator config (added in all environments, but with different permissions depending on the environment)
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.health.only-when-up=true
management.security.enabled=false  # O enable only in production if necessary
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


