# Default connection pool
spring.datasource.hikari.connectionTimeout=30000
spring.datasource.hikari.maximumPoolSize=5
# PostgreSQL (by local environment)
spring.datasource.url=jdbc:postgresql://localhost:5432/myvanitydb
spring.datasource.username=myvanity
spring.datasource.password=password
# Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# other config
server.port=8080
logging.level.org.springframework=DEBUG
