# Base configuration for all environments
---
spring:
  application:
    name: myvanitys-api
  profiles:
    active: local
openapi:
  myVanitysProduct:
    base-path: /api/v1


server:
  servlet:
    context-path: /myvanitys
  port: 8080

# Actuator configuration
management:
  server:
    base-path: /actuator
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      only-when-up: true
      probes:
        enabled: true

# OAuth Configuration base
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}

# JWT Configuration base
jwt:
  secret: ${JWT_SECRET:defaultSecretKeyForDevelopmentPurposesOnlyDoNotUseInProduction}
  expiration: 86400000  # 24 hours in milliseconds

# Info endpoint
info:
  app:
    name: MyVanitys API
    version: ${project.version}

springdoc:
  swagger-ui:
    path: /myvanitys/swagger-ui.html
  api-docs:
    path: /myvanitys/v3/api-docs
