server:
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: dev

management:
  server:
    base-path: /actuator
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
info:
  app:
    name: MyVanitys API
    version: ${project.version}
