---
spring:
  datasource:
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/myvanitysdb
    username: myvanitys
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

google:
  oauth2:
    client-id: 780556869332-1sf3nmlm6df03r73jnh8a5kll8ev3ifo.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:5173/callback

management:
  security:
    enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG
      springframework: DEBUG

# Local environment overrides
jwt:
  secret: "local_development_secret_key_which_is_at_least_32_chars_long"
  expiration: 86400  # 24 hours in seconds for easier development
  issuer: "myvanitys-local"

