package com.myvanitys.api;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;

import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.core.importer.Location;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchIgnore;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;

/**
 * Hexagonal architecture rules for myvanitys-api.
 *
 * Baseline established via a read-only audit (see /doc, PR description, or project notes for the full report). Rules below are split into
 * two groups:
 *
 * 1. SAFE RULES — confirmed zero violations at audit time, plus rules fixed and confirmed since. Active immediately. 2. KNOWN-VIOLATION
 * RULE — real architecture debt confirmed by the audit, still unresolved. Kept as @ArchIgnore with a TODO until the corresponding refactor
 * ticket is closed. Do NOT delete; re-enable once fixed, so the rule keeps protecting the boundary going forward.
 */
@AnalyzeClasses(
    packages = "com.myvanitys.api",
    importOptions = {
        ImportOption.DoNotIncludeTests.class,
        ArchitectureTest.DoNotIncludeGeneratedApiClasses.class
    }
)
class ArchitectureTest {

  /**
   * Excludes com.myvanitys.api.rest.v1.* — classes generated by OpenAPI Generator from the myvanitys-api-spec dependency (e.g.
   * AuthenticationApiController, ProductsApiController). These are not part of the hand-written hexagonal structure and would otherwise be
   * pulled in because @AnalyzeClasses scans the whole classpath under "com.myvanitys.api", including code shipped inside dependency jars.
   */
  static final class DoNotIncludeGeneratedApiClasses implements ImportOption {

    @Override
    public boolean includes(Location location) {
      return !location.contains("com/myvanitys/api/rest/v1");
    }
  }

  // ------------------------------------------------------------------
  // 1. SAFE RULES — zero violations confirmed, active now
  //    (includes rules fixed and re-enabled since the original audit)
  // ------------------------------------------------------------------

  @ArchTest
  static final ArchRule domain_does_not_depend_on_infrastructure =
      noClasses()
          .that().resideInAPackage("..domain..")
          .should().dependOnClassesThat().resideInAPackage("..infrastructure..");

  @ArchTest
  static final ArchRule domain_does_not_depend_on_application =
      noClasses()
          .that().resideInAPackage("..domain..")
          .should().dependOnClassesThat().resideInAPackage("..application..");

  @ArchTest
  static final ArchRule primary_adapters_do_not_depend_on_secondary_adapters =
      noClasses()
          .that().resideInAPackage("..infrastructure.adapter.primary..")
          .should().dependOnClassesThat().resideInAPackage("..infrastructure.adapter.secondary..");

  @ArchTest
  static final ArchRule controllers_only_in_primary_adapter =
      noClasses()
          .that().haveSimpleNameEndingWith("Controller")
          .should().resideOutsideOfPackage("..infrastructure.adapter.primary..");

  @ArchTest
  static final ArchRule repository_adapters_only_in_secondary_adapter =
      noClasses()
          .that().haveSimpleNameEndingWith("RepositoryAdapter")
          .should().resideOutsideOfPackage("..infrastructure.adapter.secondary..");

  /**
   * RESOLVED: ProductReview no longer carries @Service — Spring wiring moved to product.infrastructure.config.ProductReviewConfig instead.
   * Rule confirmed passing; now enforced permanently.
   */
  @ArchTest
  static final ArchRule domain_does_not_depend_on_spring =
      noClasses()
          .that().resideInAPackage("..domain..")
          .should().dependOnClassesThat().resideInAnyPackage("org.springframework..");

  // ------------------------------------------------------------------
  // 2. KNOWN-VIOLATION RULE — real debt, disabled pending refactor
  // ------------------------------------------------------------------

  /**
   * TODO(ARCH-XXX): re-enable once FindProductService, FindProductByUser,
   * FindProductByTerm, and CommandToProductMapper stop importing JPA
   * entities/mappers/Spring Data repositories directly. They must go
   * through a domain.port.secondary interface instead.
   *
   * This is the core hexagonal violation found in the audit — application
   * layer reaching into infrastructure.persistence directly.
   */
  @ArchTest
  @ArchIgnore
  // TODO(ARCH-XXX): re-enable once fixed — see javadoc above
  static final ArchRule application_does_not_depend_on_persistence =
      noClasses()
          .that().resideInAPackage("..application..")
          .should().dependOnClassesThat().resideInAPackage("..infrastructure.persistence..");

  // ------------------------------------------------------------------
  // Deliberately NOT enforced yet (documented, not silently ignored):
  //
  // - RESOLVED: shared-kernel relocation cycle complete. TokenService →
  //   auth.infrastructure.security, EntityId → common.valueobject,
  //   UnauthorizedException → common. All three confirmed via the
  //   verification gate (unit + ArchUnit + integration all green).
  //   No longer tracked here.
  //
  // - Naming/location divergence between auth (application.service,
  //   application.port.primary.command) and product (application.usecase,
  //   application.command) is tolerated as-is; not a correctness risk,
  //   just inconsistency. No rule needed unless it starts causing
  //   confusion in practice.
  // ------------------------------------------------------------------
}