package com.myvanitys.api;

import static com.tngtech.archunit.lang.syntax.ArchRuleDefinition.noClasses;

import com.tngtech.archunit.core.importer.ImportOption;
import com.tngtech.archunit.core.importer.Location;
import com.tngtech.archunit.junit.AnalyzeClasses;
import com.tngtech.archunit.junit.ArchTest;
import com.tngtech.archunit.lang.ArchRule;

/**
 * Hexagonal architecture rules for myvanitys-api.
 *
 * Established via a read-only audit that found several real violations (see project history for the full report and the refactor phases
 * that fixed each one: TokenService/EntityId/UnauthorizedException relocation to close cross-context leaks, ProductReview's Spring
 * dependency removed from domain, and FindProductService's persistence coupling replaced with proper ProductRepository port methods).
 *
 * All 7 rules below are active with zero known violations. If a future change breaks one, that is a real architecture regression to fix —
 * not a rule to loosen.
 */
@AnalyzeClasses(
    packages = "com.myvanitys.api",
    importOptions = {
        ImportOption.DoNotIncludeTests.class,
        ArchitectureTest.DoNotIncludeGeneratedApiClasses.class
    }
)
class ArchitectureTest {

  /**
   * Excludes com.myvanitys.api.rest.v1.* — classes generated by OpenAPI Generator from the myvanitys-api-spec dependency (e.g.
   * AuthenticationApiController, ProductsApiController). These are not part of the hand-written hexagonal structure and would otherwise be
   * pulled in because @AnalyzeClasses scans the whole classpath under "com.myvanitys.api", including code shipped inside dependency jars.
   */
  static final class DoNotIncludeGeneratedApiClasses implements ImportOption {

    @Override
    public boolean includes(Location location) {
      return !location.contains("com/myvanitys/api/rest/v1");
    }
  }

  // ------------------------------------------------------------------
  // All rules confirmed passing, zero violations, zero exceptions.
  //
  // Note: auth and product diverge in naming/location for otherwise
  // equivalent concepts (auth uses application.service +
  // application.port.primary.command; product uses application.usecase +
  // application.command). This is tolerated inconsistency, not a
  // violation of any rule above — no ArchUnit rule targets it.
  // ------------------------------------------------------------------

  @ArchTest
  static final ArchRule domain_does_not_depend_on_infrastructure =
      noClasses()
          .that().resideInAPackage("..domain..")
          .should().dependOnClassesThat().resideInAPackage("..infrastructure..");

  @ArchTest
  static final ArchRule domain_does_not_depend_on_application =
      noClasses()
          .that().resideInAPackage("..domain..")
          .should().dependOnClassesThat().resideInAPackage("..application..");

  @ArchTest
  static final ArchRule primary_adapters_do_not_depend_on_secondary_adapters =
      noClasses()
          .that().resideInAPackage("..infrastructure.adapter.primary..")
          .should().dependOnClassesThat().resideInAPackage("..infrastructure.adapter.secondary..");

  @ArchTest
  static final ArchRule controllers_only_in_primary_adapter =
      noClasses()
          .that().haveSimpleNameEndingWith("Controller")
          .should().resideOutsideOfPackage("..infrastructure.adapter.primary..");

  @ArchTest
  static final ArchRule repository_adapters_only_in_secondary_adapter =
      noClasses()
          .that().haveSimpleNameEndingWith("RepositoryAdapter")
          .should().resideOutsideOfPackage("..infrastructure.adapter.secondary..");

  @ArchTest
  static final ArchRule domain_does_not_depend_on_spring =
      noClasses()
          .that().resideInAPackage("..domain..")
          .should().dependOnClassesThat().resideInAnyPackage("org.springframework..");

  @ArchTest
  static final ArchRule application_does_not_depend_on_persistence =
      noClasses()
          .that().resideInAPackage("..application..")
          .should().dependOnClassesThat().resideInAPackage("..infrastructure.persistence..");

}